import {
  Column,
  CreateDateColumn,
  Entity,
  PrimaryColumn,
  UpdateDateColumn,
} from 'typeorm';

export type SignalSide = 'BUY' | 'SELL';
export type SignalStatus = 'PENDING' | 'OPENED' | 'CLOSED' | 'CANCELLED';

@Entity('signals')
export class Signal {
  // Id is generated by the Telegram bot (not the DB) so the bot can
  // reference it in a later /trade update before the row even exists.
  @PrimaryColumn('uuid')
  id: string;

  @Column()
  symbol: string;

  @Column({ type: 'varchar' })
  side: SignalSide;

  @Column({ type: 'decimal', precision: 18, scale: 8 })
  entry: string;

  @Column({ type: 'decimal', precision: 18, scale: 8, nullable: true })
  stopLoss: string | null;

  @Column({ type: 'jsonb', default: () => "'[]'" })
  takeProfit: string[];

  @Column({ type: 'varchar', nullable: true })
  source: string | null;

  @Column({ type: 'varchar', default: 'PENDING' })
  status: SignalStatus;

  @Column({ type: 'decimal', precision: 18, scale: 8, nullable: true })
  executionPrice: string | null;

  @Column({ type: 'decimal', precision: 18, scale: 8, nullable: true })
  pnl: string | null;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
